/**
 * @license
 * Copyright (c) 2025-present Relteco LLC. All rights reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { describe, it, expect } from 'vitest';
import { generateCSS, cssVar } from './generate';
import { themes } from '../themes';

describe('generateCSS', () => {
  const css = generateCSS(themes);

  it('CSS çıktısı boş olmamalı / should generate non-empty CSS', () => {
    expect(css).toBeTruthy();
    expect(css.length).toBeGreaterThan(100);
  });

  it('header yorum satırını içermeli / should include header comment', () => {
    expect(css).toContain('Generated by @relteco/relui-tokens');
  });

  it(':root bloğu olmalı (statik token\'lar) / should have :root block for static tokens', () => {
    expect(css).toContain(':root {');
  });

  it('tüm tema varyantları için data-theme selector olmalı / should have data-theme selectors', () => {
    expect(css).toContain('[data-theme="default-dark"]');
    expect(css).toContain('[data-theme="default-light"]');
    expect(css).toContain('[data-theme="ocean-dark"]');
    expect(css).toContain('[data-theme="ocean-light"]');
    expect(css).toContain('[data-theme="forest-dark"]');
    expect(css).toContain('[data-theme="forest-light"]');
  });

  it('--rel- prefix ile CSS variable\'lar olmalı / should use --rel- prefix', () => {
    expect(css).toContain('--rel-color-bg-app');
    expect(css).toContain('--rel-color-fg-default');
    expect(css).toContain('--rel-color-accent-default');
    expect(css).toContain('--rel-spacing-4');
    expect(css).toContain('--rel-radius-md');
    expect(css).toContain('--rel-text-base');
    expect(css).toContain('--rel-shadow-md');
    expect(css).toContain('--rel-z-modal');
    expect(css).toContain('--rel-duration-normal');
    expect(css).toContain('--rel-ease-ease-in-out');
  });

  it('statik token\'lar doğru değerlere sahip olmalı / static tokens should have correct values', () => {
    expect(css).toContain('--rel-spacing-4: 1rem');
    expect(css).toContain('--rel-radius-full: 9999px');
  });
});

describe('cssVar', () => {
  it('tüm semantic key\'ler mevcut olmalı / should have all semantic keys', () => {
    expect(cssVar.bgApp).toBe('var(--rel-color-bg-app)');
    expect(cssVar.fgDefault).toBe('var(--rel-color-fg-default)');
    expect(cssVar.accentDefault).toBe('var(--rel-color-accent-default)');
    expect(cssVar.destructiveDefault).toBe('var(--rel-color-destructive-default)');
    expect(cssVar.inputBg).toBe('var(--rel-color-input-bg)');
    expect(cssVar.surfaceRaised).toBe('var(--rel-color-surface-raised)');
  });

  it('tüm değerler var() ile sarılmış olmalı / all values should be wrapped in var()', () => {
    for (const value of Object.values(cssVar)) {
      expect(value).toMatch(/^var\(--rel-color-.+\)$/);
    }
  });
});
