/**
 * @license
 * Copyright (c) 2025-present Relteco LLC. All rights reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/**
 * CSS Variables generator — generates CSS custom properties from theme tokens.
 * CSS değişken üretici — tema token'larından CSS custom properties üretir.
 *
 * @packageDocumentation
 */

import type { SemanticColors, ThemeDefinition, ThemeVariant } from '../themes/types';
import { spacing } from '../primitives/spacing';
import { radius } from '../primitives/radius';
import { fontSize, fontFamily, fontWeight, lineHeight, letterSpacing } from '../primitives/typography';
import { shadow, shadowDark } from '../primitives/shadow';
import { zIndex } from '../primitives/z-index';
import { duration, easing } from '../primitives/animation';

/** CSS variable prefix / CSS değişken öneki */
const PREFIX = '--rel' as const;

/**
 * Camel case'i kebab case'e çevir.
 * Convert camelCase to kebab-case.
 */
function toKebab(str: string): string {
  return str.replace(/([A-Z])/g, '-$1').toLowerCase();
}

/**
 * Semantic renk token'larından CSS variable string üret.
 * Generate CSS variable declarations from semantic color tokens.
 */
function colorVarsFromTheme(colors: SemanticColors): string {
  const lines: string[] = [];
  for (const [key, value] of Object.entries(colors)) {
    lines.push(`  ${PREFIX}-color-${toKebab(key)}: ${value};`);
  }
  return lines.join('\n');
}

/**
 * Statik token'lardan (spacing, radius, vb.) CSS variable string üret.
 * Generate CSS variable declarations from static tokens.
 */
function staticVars(): string {
  const lines: string[] = [];

  // Spacing
  for (const [key, value] of Object.entries(spacing)) {
    lines.push(`  ${PREFIX}-spacing-${key}: ${value};`);
  }

  // Radius
  for (const [key, value] of Object.entries(radius)) {
    lines.push(`  ${PREFIX}-radius-${key}: ${value};`);
  }

  // Font family
  for (const [key, value] of Object.entries(fontFamily)) {
    lines.push(`  ${PREFIX}-font-${key}: ${value};`);
  }

  // Font size
  for (const [key, value] of Object.entries(fontSize)) {
    lines.push(`  ${PREFIX}-text-${key}: ${value};`);
  }

  // Font weight
  for (const [key, value] of Object.entries(fontWeight)) {
    lines.push(`  ${PREFIX}-font-${key}: ${value};`);
  }

  // Line height
  for (const [key, value] of Object.entries(lineHeight)) {
    lines.push(`  ${PREFIX}-leading-${key}: ${value};`);
  }

  // Letter spacing
  for (const [key, value] of Object.entries(letterSpacing)) {
    lines.push(`  ${PREFIX}-tracking-${key}: ${value};`);
  }

  // Z-index
  for (const [key, value] of Object.entries(zIndex)) {
    lines.push(`  ${PREFIX}-z-${key}: ${value};`);
  }

  // Duration
  for (const [key, value] of Object.entries(duration)) {
    lines.push(`  ${PREFIX}-duration-${key}: ${value};`);
  }

  // Easing
  for (const [key, value] of Object.entries(easing)) {
    lines.push(`  ${PREFIX}-ease-${toKebab(key)}: ${value};`);
  }

  return lines.join('\n');
}

/**
 * Shadow token'larından CSS variable string üret (tema bazlı).
 * Generate shadow CSS variables (theme-aware).
 */
function shadowVars(mode: 'dark' | 'light'): string {
  const source = mode === 'dark' ? shadowDark : shadow;
  const lines: string[] = [];
  for (const [key, value] of Object.entries(source)) {
    lines.push(`  ${PREFIX}-shadow-${key}: ${value};`);
  }
  return lines.join('\n');
}

/**
 * Tek bir tema için CSS bloğu üret.
 * Generate CSS block for a single theme.
 */
function themeBlock(theme: ThemeDefinition, variant: ThemeVariant): string {
  const selector = `[data-theme="${variant}"]`;
  const colorLines = colorVarsFromTheme(theme.colors);
  const shadowLines = shadowVars(theme.mode);

  return `${selector} {\n${colorLines}\n${shadowLines}\n}`;
}

/**
 * Tüm temaların CSS çıktısını üret.
 * Generate full CSS output for all themes.
 *
 * @param themes - Tema varyantları ve tanımları / Theme variants and definitions
 * @returns CSS string
 */
export function generateCSS(themeMap: Record<ThemeVariant, ThemeDefinition>): string {
  const parts: string[] = [];

  // Header
  parts.push('/* Generated by @relteco/relui-tokens — DO NOT EDIT */');
  parts.push('');

  // Static tokens (root)
  parts.push(`:root {\n${staticVars()}\n}`);
  parts.push('');

  // Theme-specific tokens
  for (const [variant, theme] of Object.entries(themeMap)) {
    parts.push(themeBlock(theme, variant as ThemeVariant));
    parts.push('');
  }

  // Default theme fallback (dark)
  const defaultDark = themeMap['default-dark'];
  if (defaultDark) {
    parts.push(`:root {\n${colorVarsFromTheme(defaultDark.colors)}\n${shadowVars('dark')}\n}`);
    parts.push('');
  }

  return parts.join('\n');
}

/**
 * Tema CSS variable referansları — bileşenlerde kullanılacak.
 * Theme CSS variable references — to be used in components.
 *
 * Örnek / Example: `cssVar.bgApp` → `var(--rel-color-bg-app)`
 */
export const cssVar = Object.fromEntries(
  [
    'bgApp', 'bgSubtle', 'bgComponent', 'bgComponentHover', 'bgComponentActive', 'bgOverlay',
    'fgDefault', 'fgMuted', 'fgDisabled', 'fgInverse',
    'borderDefault', 'borderHover', 'borderFocus', 'borderSubtle',
    'accentDefault', 'accentHover', 'accentActive', 'accentFg', 'accentSubtle', 'accentSubtleFg',
    'destructiveDefault', 'destructiveHover', 'destructiveFg', 'destructiveSubtle', 'destructiveSubtleFg',
    'successDefault', 'successHover', 'successFg', 'successSubtle', 'successSubtleFg',
    'warningDefault', 'warningHover', 'warningFg', 'warningSubtle', 'warningSubtleFg',
    'infoDefault', 'infoHover', 'infoFg', 'infoSubtle', 'infoSubtleFg',
    'inputBg', 'inputBorder', 'inputBorderFocus', 'inputPlaceholder',
    'surfaceRaised', 'surfaceOverlay', 'surfaceSunken',
    'shadowColor',
  ].map((key) => [key, `var(${PREFIX}-color-${toKebab(key)})`]),
) as Record<keyof SemanticColors, string>;
